// Regenerates the docs-site chart gallery data from @chitra/core.
//
//   tsx scripts/generate-charts.ts          # write files
//   tsx scripts/generate-charts.ts --check  # verify on-disk files are current
//
// Outputs (all DERIVED from scripts/chart-specs.ts — never edit by hand):
//   src/data/ansi-charts.json       { [id]: coloredAnsiString }
//   src/data/svg-charts.json        { [id]: svgMarkup }   (only for charts with svg())
//   src/data/charts.ts              export const CHARTS: ChartDef[]
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { SPECS } from "./chart-specs.js";

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = resolve(here, "../src/data");
const ANSI_JSON = resolve(dataDir, "ansi-charts.json");
const SVG_JSON = resolve(dataDir, "svg-charts.json");
const CHARTS_TS = resolve(dataDir, "charts.ts");

/** Escape a string for safe embedding inside a TS template literal. */
function tl(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function buildAnsiJson(): string {
  const obj: Record<string, string> = {};
  for (const spec of SPECS) obj[spec.id] = spec.ansi();
  return JSON.stringify(obj, null, 2) + "\n";
}

function buildSvgJson(): string {
  const obj: Record<string, string> = {};
  for (const spec of SPECS) {
    if (spec.svg) {
      const svg = spec.svg();
      if (svg) obj[spec.id] = svg;
    }
  }
  return JSON.stringify(obj, null, 2) + "\n";
}

function buildChartsTs(): string {
  const header = `// AUTO-GENERATED by scripts/generate-charts.ts from scripts/chart-specs.ts.
// Do not edit by hand — run \`pnpm gen:charts\` to regenerate.

export interface ChartDef {
  id: string;
  name: string;
  description: string;
  preview: string;
  code: string;
}

export const CHARTS: ChartDef[] = [
`;
  const entries = SPECS.map((spec) => {
    const preview = tl(spec.plain());
    const code = tl(spec.code);
    return `  {
    id: ${JSON.stringify(spec.id)},
    name: ${JSON.stringify(spec.name)},
    description: ${JSON.stringify(spec.description)},
    preview: \`${preview}\`,
    code: \`${code}\`,
  },
`;
  }).join("");
  return header + entries + "];\n";
}

const outputs = [
  { path: ANSI_JSON, label: "src/data/ansi-charts.json", content: buildAnsiJson() },
  { path: SVG_JSON, label: "src/data/svg-charts.json", content: buildSvgJson() },
  { path: CHARTS_TS, label: "src/data/charts.ts", content: buildChartsTs() },
];

const check = process.argv.includes("--check");
let drifted = 0;

for (const out of outputs) {
  if (check) {
    let current = "";
    try {
      current = readFileSync(out.path, "utf8");
    } catch {
      /* missing file counts as drift */
    }
    if (current !== out.content) {
      drifted++;
      console.error(`✗ ${out.label} is STALE — run \`pnpm gen:charts\``);
    } else {
      console.log(`✓ ${out.label} up to date`);
    }
  } else {
    writeFileSync(out.path, out.content);
    console.log(`wrote ${out.label} (${SPECS.length} charts)`);
  }
}

if (check && drifted > 0) {
  console.error(`\n${drifted} file(s) out of sync with chart-specs.ts.`);
  process.exit(1);
}
