// GENERATED by scripts/sync-version.mjs — do not edit by hand.
// Run `node scripts/sync-version.mjs` after bumping packages/core/package.json.
// CI runs it with --check, so this file cannot drift from the manifest.
export const VERSION = "0.3.0";
