// AUTO-GENERATED by scripts/generate-charts.ts from scripts/chart-specs.ts.
// Do not edit by hand — run `pnpm gen:charts` to regenerate.

export interface ChartDef {
  id: string;
  name: string;
  description: string;
  preview: string;
  code: string;
  /** Semantic nav category (authored in chart-specs.ts). */
  group: string;
}

export const CHARTS: ChartDef[] = [
  {
    id: "line",
    name: "Line Chart",
    description: "Continuous data over time, rendered with explicit ASCII line characters matching classical terminal monitoring.",
    preview: `┌╌ NIFTY 50 INDEX ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ TREND                                                                │
│ ──*── Series 1                                                       │
│ 24.9K+*                                                              │
│      │                                                               │
│      │/*                                                             │
│ 24.7K│*\\                                                             │
│      │/*\\/                                                           │
│      │/**\\*                                                          │
│ 24.5K│***/**\\                                                        │
│      │**\\                                                            │
│      │/*\\*                                                           │
│ 24.3K│***\\                                                           │
│      │*                                                              │
│      │*\\/                                                            │
│ 24.1K│****                                                           │
│      │**\\                                                            │
│      │\\*                                                             │
│ 23.9K│                                                               │
│           +      +       +      +       +      +       +      +      │
│        7D Ago 6D Ago  5D Ago 4D Ago  3D Ago 2D Ago  1D Ago   Now     │
│ * Series 1 · lowest 23.9K · highest 24.9K · avg 24.4K · last 24.6K   │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { line } from "@ifelse.codes/chitra";

line({
  data: [
    24000, 24080, 24150, 24260, 24400, 24460, 24380, 24400, 24340, 24310,
    24480, 24390, 24270, 24140, 24060, 24060, 23990, 23880, 23940, 23900,
    24060, 24000, 24060, 24120, 24180, 24260, 24280, 24240, 24350, 24340,
    24460, 24470, 24490, 24510, 24550, 24600, 24660, 24800, 24860, 24860,
    24720, 24660, 24630, 24590, 24540, 24510, 24470, 24520, 24560, 24600
  ],
  labels: ["7D Ago", "6D Ago", "5D Ago", "4D Ago", "3D Ago", "2D Ago", "1D Ago", "Now"],
  title: "NIFTY 50 INDEX",
  width: 72,
  height: 18,
  theme: "default",
  renderer: "ascii", // Forces explicit line drawing (- / \\ o)
}).render();`,
    group: "Trend & time",
  },
  {
    id: "bar",
    name: "Bar Chart",
    description: "Vertical bars for comparing categorical values, with optional grouping and stacking.",
    preview: `┌╌ Monthly Sales ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ VALUES                                  │
│ 72+        █                            │
│   │  █     █                            │
│ 56│  █   █ █ █                          │
│   │  █   █ █ █                          │
│ 40│█ █   █ █ █                          │
│   │█ █ █ █ █ █                          │
│ 24│█ █ █ █ █ █                          │
│   │█ █ █ █ █ █                          │
│  8│█ █ █ █ █ █                          │
│  0│█ █ █ █ █ █                          │
│    + + + + + +                          │
│    JaFeMaApMaJ                          │
│ ■ Series 1 · avg 55.83 · peak 72 ▂▇▅█▆  │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { bar } from "@ifelse.codes/chitra";

bar({
  data: [42, 67, 38, 55, 72, 61],
  labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
  title: "Monthly Sales",
  height: 10,
}).render();`,
    group: "Comparison",
  },
  {
    id: "area",
    name: "Area Chart",
    description: "Like a line chart but with the area below filled in — great for volume/accumulation.",
    preview: `┌╌ Area Chart ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ TREND                                            │
│ 52│                                        ⢀⣠⣾   │
│ 46│                             ⢀⣴⣤⣀⡀    ⢀⣴⣿⣿⣿   │
│ 40│                           ⢀⣴⣿⣿⣿⣿⣿⣷⣦⣤⣶⣿⣿⣿⣿⣿   │
│ 34│                 ⣠⣶⣦⣤⣀   ⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿   │
│ 28│               ⢀⣴⣿⣿⣿⣿⣿⣿⣶⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿   │
│ 22│              ⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿   │
│ 16│   ⣀⣤⣾⣿⣿⣶⣦⣤⣀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿   │
│ 10│⣠⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿   │
│ series · highest 52 · lowest 10 · last 52        │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { area } from "@ifelse.codes/chitra";

area({
  data: [10, 20, 15, 35, 28, 45, 38, 52],
  title: "Area Chart",
  width: 52,
  height: 10,
}).render();`,
    group: "Trend & time",
  },
  {
    id: "sparkline",
    name: "Sparkline",
    description: "Compact inline charts — perfect for dashboards, logs, and status readouts.",
    preview: `┌╌ CPU ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ SPARKLINE             │
│             ██  ████  │
│         ▓▓▓▓██▓▓████  │
│   ░░▒▒▒▒▓▓▓▓██▓▓████  │
│ ░░░░▒▒▒▒▓▓▓▓██▓▓████  │
│ 10 readings · peak 82 │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘
┌╌ MEM ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ SPARKLINE             │
│                   ██  │
│           ▓▓▓▓▓▓████  │
│     ▒▒░░▒▒▓▓▓▓▓▓████  │
│ ░░░░▒▒░░▒▒▓▓▓▓▓▓████  │
│ 10 readings · peak 78 │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘
┌╌ NET ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ SPARKLINE             │
│                 ████  │
│         ▓▓▓▓██▓▓████  │
│ ▒▒  ▒▒  ▓▓▓▓██▓▓████  │
│ ▒▒░░▒▒░░▓▓▓▓██▓▓████  │
│ 10 readings · peak 30 │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { sparkline } from "@ifelse.codes/chitra";

// Unicode blocks (default)
sparkline({ data: [45, 52, 61, 58, 70, 65, 78, 72, 80, 82],
  label: "CPU", showValue: true }).render();

// Braille renderer
sparkline({ data: [60, 62, 65, 63, 68, 70, 72, 69, 74, 78],
  label: "MEM", renderer: "braille" }).render();

// ASCII fallback
sparkline({ data: [12, 8, 15, 6, 20, 18, 25, 22, 30, 28],
  label: "NET", renderer: "ascii" }).render();`,
    group: "Single value & progress",
  },
  {
    id: "histogram",
    name: "Histogram",
    description: "Distribution of continuous data across configurable bins.",
    preview: `┌╌ Distribution ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ DISTRIBUTION                         │
│ 5+                ███                │
│  │                ███                │
│ 4│            ███ ███                │
│  │            ███ ███                │
│ 3│        ▓▓▓ ███ ███ ▓▓▓            │
│  │        ▓▓▓ ███ ███ ▓▓▓            │
│ 2│    ▒▒▒ ▓▓▓ ███ ███ ▓▓▓ ▒▒▒        │
│  │    ▒▒▒ ▓▓▓ ███ ███ ▓▓▓ ▒▒▒        │
│ 1│░░░ ▒▒▒ ▓▓▓ ███ ███ ▓▓▓ ▒▒▒ ░░░    │
│ 0│░░░ ▒▒▒ ▓▓▓ ███ ███ ▓▓▓ ▒▒▒ ░░░    │
│  └╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│   1   2   3   4   5   5   6   7      │
│ 21 samples · peak 4.50               │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { histogram } from "@ifelse.codes/chitra";

histogram({
  data: [1,2,2,3,3,3,4,4,4,4,5,5,5,5,5,6,6,6,7,7,8],
  bins: 8,
  title: "Distribution",
  height: 10,
  width: 40,
}).render();`,
    group: "Distribution & density",
  },
  {
    id: "scatter",
    name: "Scatter Plot",
    description: "Two-dimensional point data for spotting correlations and clusters.",
    preview: `┌╌ Scatter Plot ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ CORRELATION                                    │
│ 12+                                          ⠈ │
│   │                                            │
│ 10│                                            │
│   │                       ⠠                    │
│  8│                                            │
│   │              ⡀                             │
│  7│                                            │
│   │                            ⠈               │
│  5│                   ⠂                        │
│   │    ⠠                                       │
│  3│         ⠠                                  │
│  2│⡀                                           │
│ 8 points · peak (10, 12)                       │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { scatter } from "@ifelse.codes/chitra";

scatter({
  data: [
    {x:1,y:2}, {x:2,y:4}, {x:3,y:3}, {x:4,y:7},
    {x:5,y:5}, {x:6,y:9}, {x:7,y:6}, {x:10,y:12},
  ],
  title: "Scatter Plot",
  width: 50,
  height: 12,
}).render();`,
    group: "Comparison",
  },
  {
    id: "pie",
    name: "Pie Chart",
    description: "Circular proportional chart for showing part-to-whole relationships.",
    preview: `┌╌ PIE ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│            ⢀⢈⣌⣌⣌⣌⣌⣌⣌⢈⠈                                    │
│        ⢀⣌⣮⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣮⣌⠈                                │
│      ⣈⣮⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣮⢌                              │
│    ⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⠈                            │
│   ⣨⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢎                           │
│  ⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠎                          │
│ ⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠈   █ Organic  35 (35.0%) │
│ ⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏   █ Direct   25 (25.0%) │
│ ⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏   █ Social   20 (20.0%) │
│ ⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏   █ Email    12 (12.0%) │
│ ⠐⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁   █ Paid       8 (8.0%) │
│  ⡰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇                          │
│   ⡱⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠗                           │
│    ⠐⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁                            │
│      ⠱⡷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡷⠓                              │
│        ⠐⠳⡷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡷⠳⠁                                │
│            ⠐⠑⠳⠳⠳⠳⠳⠳⠳⠑⠁                                    │
│ 5 slices · total 100                                      │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { pie } from "@ifelse.codes/chitra";

pie({
  data: [35, 25, 20, 12, 8],
  labels: ["Organic", "Direct", "Social", "Email", "Paid"],
}).render();`,
    group: "Part-to-whole",
  },
  {
    id: "donut",
    name: "Donut Chart",
    description: "Pie chart with a hollow centre — great for showing a primary metric.",
    preview: `┌╌ DONUT ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ DISTRIBUTION                                                 │
│            ⢀⢈⣌⣌⣌⣌⣌⣌⣌⢈⠈                                       │
│        ⢀⣌⣮⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣮⣌⠈                                   │
│      ⣈⣮⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣮⢌                                 │
│    ⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⠈                               │
│   ⣨⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⡷⠳⠳⠳⡷⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢎                              │
│  ⣠⣿⣿⣿⣿⣿⣿⣿⣿⡿⠓⠁       ⠐⠱⣷⣿⣿⣿⣿⣿⣿⣿⣿⠎                             │
│ ⢀⣿⣿⣿⣿⣿⣿⣿⣿⠿             ⣳⣿⣿⣿⣿⣿⣿⣿⣿⠈   █ TypeScript  30 (30.0%) │
│ ⣰⣿⣿⣿⣿⣿⣿⣿⡿               ⣷⣿⣿⣿⣿⣿⣿⣿⠏   █ Python      25 (25.0%) │
│ ⣰⣿⣿⣿⣿⣿⣿⣿⠏      100      ⣰⣿⣿⣿⣿⣿⣿⣿⠏   █ Rust        22 (22.0%) │
│ ⣰⣿⣿⣿⣿⣿⣿⣿⣯               ⣾⣿⣿⣿⣿⣿⣿⣿⠏   █ Go          15 (15.0%) │
│ ⠐⣿⣿⣿⣿⣿⣿⣿⣿⣏             ⣼⣿⣿⣿⣿⣿⣿⣿⣿⠁   █ Other         8 (8.0%) │
│  ⡰⣿⣿⣿⣿⣿⣿⣿⣿⣯⢌⠈       ⢀⣈⣾⣿⣿⣿⣿⣿⣿⣿⣿⠇                             │
│   ⡱⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⣮⣌⣌⣌⣮⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠗                              │
│    ⠐⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁                               │
│      ⠱⡷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡷⠓                                 │
│        ⠐⠳⡷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡷⠳⠁                                   │
│            ⠐⠑⠳⠳⠳⠳⠳⠳⠳⠑⠁                                       │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { donut } from "@ifelse.codes/chitra";

donut({
  data: [30, 25, 22, 15, 8],
  labels: ["TypeScript", "Python", "Rust", "Go", "Other"],
}).render();`,
    group: "Part-to-whole",
  },
  {
    id: "heatmap",
    name: "Heatmap",
    description: "2D grid whose intensity is a grey tone ramp, with the single peak cell marked in the accent hue.",
    preview: `┌╌ Activity Heatmap ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ DENSITY                              │
│    0  1  2  3  4                     │
│  0+░░░░░░▒▒▒▓▓▓▓▓▓                   │
│  1│░░░▒▒▒▒▒▒▓▓▓███                   │
│  2│░░░▒▒▒▓▓▓▓▓▓███                   │
│  3│▒▒▒▒▒▒▓▓▓██████                   │
│                                      │
│                                      │
│                                      │
│ 4×5 grid · peak (3, 4)               │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { heatmap } from "@ifelse.codes/chitra";

heatmap({
  data: [
    [1, 3, 5, 7, 9],
    [2, 4, 6, 8, 10],
    [3, 5, 7, 9, 11],
    [4, 6, 8, 10, 12],
  ],
  title: "Activity Heatmap",
  width: 40,
  height: 8,
}).render();`,
    group: "Distribution & density",
  },
  {
    id: "progress",
    name: "Progress Bar",
    description: "Single-value progress panel in the locked design language — grey-tone fill with an accented leading edge. Great for build steps, quotas, and budgets.",
    preview: `┌╌ PROGRESS ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ BUILD                            │
│ ████████████████████████████──── │
│ +╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌+ │
│ 0                            100 │
│ 87 of 0..100 · 87.0%             │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘
┌╌ PROGRESS ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ TESTS                            │
│ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█──────────── │
│ +╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌+ │
│ 0                            100 │
│ 62 of 0..100 · 62.0%             │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘
┌╌ PROGRESS ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ COVERAGE                         │
│ ▒▒▒▒▒▒▒▒▒▒█───────────────────── │
│ +╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌+ │
│ 0                            100 │
│ 34 of 0..100 · 34.0%             │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { progress } from "@ifelse.codes/chitra";

progress({ value: 87, label: "Build" }).render();
progress({ value: 62, label: "Tests" }).render();
progress({ value: 34, label: "Coverage" }).render();`,
    group: "Single value & progress",
  },
  {
    id: "gauge",
    name: "Gauge",
    description: "Single-value meter in the locked panel language — grey-tone fill with an accented reading edge. Great for KPIs, CPU usage, battery level.",
    preview: `┌╌ GAUGE ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ CPU LOAD                             │
│ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█────────── │
│ +╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌+ │
│ 0                                100 │
│ 73 of 0..100 · 73.0%                 │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { gauge } from "@ifelse.codes/chitra";

gauge({
  value: 73,
  min: 0,
  max: 100,
  label: "CPU Load",
  width: 40,
}).render();`,
    group: "Single value & progress",
  },
  {
    id: "horizontalBar",
    name: "Horizontal Bar",
    description: "Bars running left-to-right — ideal for ranked lists and comparisons.",
    preview: `┌╌ HORIZONTAL BAR ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ VALUES                           │
│ TypeScript █████████████████ 892 │
│ Python     ████████████▂     645 │
│ Rust       ██████████▁       534 │
│ Go         ████████          421 │
│ Ruby       █████▄            289 │
│            +╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌+     │
│            0             892     │
│ 5 items · peak TypeScript (892)  │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { horizontalBar } from "@ifelse.codes/chitra";

horizontalBar({
  data: [892, 645, 534, 421, 289],
  labels: ["TypeScript", "Python", "Rust", "Go", "Ruby"],
}).render();`,
    group: "Comparison",
  },
  {
    id: "timeline",
    name: "Timeline / Gantt",
    description: "Gantt-style spans on a shared time scale — grey tone ramp by span length, with the single longest span marked in the accent hue.",
    preview: `┌╌ Sprint Timeline ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ SPAN                                             │
│ Design ▒▒▒▒▒▒▒▒▒▒─────────────────────────────── │
│ Build  ──────────█████████████████████────────── │
│ Test   ──────────────────────────▒▒▒▒▒▒▒▒▒▒───── │
│ Deploy ────────────────────────────────────░░░░░ │
│        +╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌+ │
│        0                                       8 │
│ 4 events · longest Build                         │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { timeline } from "@ifelse.codes/chitra";

timeline({
  events: [
    { label: "Design", start: 0, end: 2 },
    { label: "Build",  start: 2, end: 6 },
    { label: "Test",   start: 5, end: 7 },
    { label: "Deploy", start: 7, end: 8 },
  ],
  title: "Sprint Timeline",
  width: 52,
}).render();`,
    group: "Trend & time",
  },
  {
    id: "radar",
    name: "Radar Chart",
    description: "Spider/radar chart for multi-axis comparison of a single entity.",
    preview: `┌╌ System Radar ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ AXES 6 · SERIES 1 · 0..9                                         │
│                               Speed                              │
│                                                                  │
│                              ⣀⡠⠂+⠢⡀⡀                             │
│                          ⢀⡠⠔⠊⢀⣢⡴●⣄⡂⠈⠒⠤⣀                          │
│                       ⣀⠤⠒⠁⢀⣤⠶⠛⠉⠂+⠛⢷⣄   ⠑⠢⢄⡀                      │
│                   ⢀⡠⠔⠊ ⣀⣴⠞⠋⠁⠅⡀⠄⡂⠄⡂⠄⠙⢷⣄    ⠈⠒⠤⣀                   │
│                ⣀⠤⠒⠁⢀⣠⡶⠛⠉⠅⡂⠅⡂⠅⡂⠅⡂+⡂⠅⡂⠅⠙⠷⣤⡀     ⠑⠢⢄⡀               │
│       Scale⢀⢀⢀⢀ ⣀⣤⠾⠋⠁⠂⠁⡂⠅⡂⠅⡂⠅⠂⠅⡂⠅⡂⠅⠂⠅⡂⠅⠈⠻⣦⡀⣀     ⠈⠒⠤⣀Safety      │
│            +⠁●⡴⢟⠋⠂⠁⡀⠄⡂⠅⡂⠅⠂⠁⡀⠄⡂⠅⡂⠄⡂⠅⡂⠄⡀⠁⠂⠅⠈⠻⣦⡀⠢⢄⡀  ⡀⠠ +           │
│            ⠐⢄⢹⣷+⠄⠂⠅⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⡂+⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⠈⠿⣧⡁⠑+    ⡇           │
│            ⡇  ⢻⣧⠅⡂⠅+⠁⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⡂+⠘●⣄⠅    ⡇           │
│            ⡇   ⢻⣧⡂⠅⡂⠅⡂⠅+⠅⡂⠅⡂⠅⡂⠅⠂+⠂⠅⡂⠅⡂⠅⡂+⡂⠅⡂⠅⠁⢹⣷⢸    ⡇           │
│            ⡇   ⠈⢿⣆⠅⡂⠅⡂⠅⡂⠅⡂⠅⡂+⡂⠅⡂⠁⡂⠄⡂+⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⢿⣇    ⡇           │
│            ⡇   ⢸⠘⣿⡄⡂⠅⡂⠅⡂⠅⡂⠅⡂⡇⡀⠅⡂⠅⡂⠅⡀⡇⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⠈⣿⡆   ⡇           │
│            ⡇   ⢸ ⠸⣿⡀⠅⡂⠅⡂⠅⡂⠅⡂⡇⠂⠅⡂⠄⡂⠅⠂⡇⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⡂⠸⣿⡀  ⡇           │
│            ⡇   ⢸  ⠹⣷⡀⡂⠅⡂⠅⡂⠅⡂+⡂⠅⡂⠁⡂⠅⡂+⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⢻⣧  ⡇           │
│            ⡇   ⢸  ⢀⢿⣷⠐⢄+⠅⡂⠅⡂⠅⡂⠄⡀+⡀⠅⡂⠅⡂⠅⡂+⡂⠅⡂⠅⡂⠅⡂⠅⠈⣿⡆ ⡇           │
│            ⡇   ⢸  ⢐+●⣧⣐⡂⠅⡂⠅⡂⠅⡂⠅⡂⠄⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⡂+⡂⠅⡂⠅⡂⠸⣿⡀⡇           │
│            ⡇   + ⠂ ⠑⠐⠘⠻⣦⡀⡂⠅⡂⠅⡂⠅⡂+⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⡂⠅⡀+⡂⠅⢹⣷⡇           │
│            ⡇⠠ ⠂ ⠉⠒⠤⡀   ⠈⠻⣦⡀⠂⠅⡂⠅⡂⠅⡂⠅⡂⠅⠂⠁⡀⠅⡂⠅⡂⠅⠂⠁⡀⠄⡂⠅⠔⢿⣇⠑⠄         │
│            +⠢⢄⡀    ⠈⠑⠢⢄  ⠈⢿⣆⠄⡀⠅⡂⠄⡂⠅⡀⠄⡂⠅⡂⠅⡂⠁⡀⠄⡂⣀⣠⣤⣶⣶⢿⠟●⢀⠅         │
│       Cost    ⠈⠒⠤⣀     ⠉⠒⢄⡀⠙⢷⣄⠅⡂+⡂⠅⡂⠅⡂⠅⢀⣀⣤⣴⣶⡾⠿⠛⠋⠉⠊  ⠁⠁⠁UX        │
│                   ⠑⠢⢄⡀    ⠈⠑⠢⠙⣷⣆⠂⣢⣠⣤⣴⣶⠿⠟⠛⠉⠁⣀⠤⠒⠁                  │
│                      ⠈⠒⠤⣀     ⡂⠙●⠛⡋⠉⠁  ⢀⡠⠔⠊                      │
│                          ⠑⠢⢄⡀ ⠈⠂⠂⠊  ⣀⠤⠒⠁                         │
│                             ⠈⠒⠤⣀⢂⡠⠔⠊                             │
│                                 +                                │
│                               Perf                               │
│ ● ── Series 1                                                    │
│ average 7.17 · peak UX (9)                                       │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { radar } from "@ifelse.codes/chitra";

radar({
  data: [8, 6, 9, 7, 5, 8],
  labels: ["Speed", "Safety", "UX", "Perf", "Cost", "Scale"],
  title: "System Radar",
  width: 64,
  height: 28,
}).render();`,
    group: "Comparison",
  },
  {
    id: "boxplot",
    name: "Box Plot",
    description: "Statistical summary showing median, quartiles, and whiskers.",
    preview: `┌╌ BOXPLOT ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ SPREAD                                         │
│   40+           ┬                              │
│     │           │                              │
│     │   ┬       │       ┬                      │
│ 31.3│   │      │█│      │                      │
│     │  │▓│     │█│      │                      │
│     │  │▓│     ═══     │▓│                     │
│ 22.5│  ───     │█│     │▓│                     │
│     │  │▓│     │█│     ───                     │
│     │  │▓│      │      │▓│                     │
│ 13.8│   │       ┴      │▓│                     │
│     │   ┴               │                      │
│    8│                   ┴                      │
│     └╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌                   │
│      Q1      Q2      Q3                        │
│ 3 groups · median 22 · peak Q2 (25)            │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { boxplot } from "@ifelse.codes/chitra";

boxplot({
  data: [
    [12, 18, 22, 28, 35],
    [15, 20, 25, 30, 40],
    [8,  14, 19, 25, 33],
  ],
  labels: ["Q1", "Q2", "Q3"],
  width: 50,
  height: 12,
}).render();`,
    group: "Distribution & density",
  },
  {
    id: "waterfall",
    name: "Waterfall",
    description: "Running total chart — shows cumulative effect of positive/negative values.",
    preview: `┌╌ WATERFALL ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ NET +550                                       │
│     500  −120 +80  −60  +150 550               │
│ 550+                    ▓▓▓▓┄████              │
│    │████┄┌╌╌┐ ▓▓▓▓┄┌╌╌┐ ▓▓▓▓ ████              │
│ 428│████ │  │ ▓▓▓▓ └╌╌┘┄▓▓▓▓ ████              │
│    │████ └╌╌┘┄▓▓▓▓           ████              │
│ 306│████                     ████              │
│    │████                     ████              │
│ 183│████                     ████              │
│    │████                     ████              │
│  61│████                     ████              │
│   0│████                     ████              │
│    └╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌              │
│     Star COGS Rev  OpEx Sale Tota              │
│ START 500 · Δ −120 +80 −60 +150 · TOTAL 550    │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { waterfall } from "@ifelse.codes/chitra";

waterfall({
  data: [500, -120, 80, -60, 150],
  labels: ["Start", "COGS", "Rev", "OpEx", "Sales"],
  height: 10,
  width: 50,
  showTotal: true,
}).render();`,
    group: "Flow & accumulation",
  },
  {
    id: "funnel",
    name: "Funnel Chart",
    description: "Conversion funnel — visualise drop-off across stages of a pipeline.",
    preview: `┌╌ FUNNEL ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ CONVERSION 3%                                             │
│ Visitors     █████████████████████████████ 10.0K (100%)   │
│ Sign-ups         ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 6.8K (68%)          │
│ Trials                ▒▒▒▒▒▒▒▒▒▓ 3.4K (34%)               │
│ Paid                      ░░▓ 1.2K (12%)                  │
│ Enterprise                 ▓ 340 (3%)                     │
│ IN 10.0K · OUT 340 · CONVERSION 3% · DROP Enterprise −72% │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { funnel } from "@ifelse.codes/chitra";

funnel({
  data: [10000, 6800, 3400, 1200, 340],
  labels: ["Visitors", "Sign-ups", "Trials", "Paid", "Enterprise"],
  width: 55,
}).render();`,
    group: "Part-to-whole",
  },
  {
    id: "candlestick",
    name: "Candlestick",
    description: "OHLC financial chart — open, high, low, close per period. Solid = bullish (close >= open), dashed outline = bearish; one accent marks the peak close.",
    preview: `┌╌ CHRX — 10-Day Price Action ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ OHLC                                                                 │
│   215+                                                        │      │
│      │                                                      █████    │
│      │                                                      █████    │
│      │                                                  │   █████    │
│ 194.5│                                      │     │   ▓▓▓▓▓ █████    │
│      │                                    ▓▓▓▓▓ ┌╌╌╌┐ ▓▓▓▓▓   │      │
│      │                    │     │         ▓▓▓▓▓ │   │ ▓▓▓▓▓          │
│      │                  ▓▓▓▓▓ ┌╌╌╌┐       ▓▓▓▓▓ └╌╌╌┘ ▓▓▓▓▓          │
│ 173.9│                  ▓▓▓▓▓ │   │   │   ▓▓▓▓▓   │                  │
│      │        │         ▓▓▓▓▓ │   │ ▓▓▓▓▓ ▓▓▓▓▓                      │
│      │        │     │   ▓▓▓▓▓ └╌╌╌┘ ▓▓▓▓▓                            │
│      │  │     │   ▓▓▓▓▓ ▓▓▓▓▓         │                              │
│ 153.4│▓▓▓▓▓ ┌╌╌╌┐ ▓▓▓▓▓               │                              │
│      │▓▓▓▓▓   │     │                                                │
│      │▓▓▓▓▓         │                                                │
│   138│  │                                                            │
│      └╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌    │
│       Jan 8 Jan 9 Jan10 Jan11 Jan12 Jan15 Jan16 Jan17 Jan18 Jan19    │
│ 10 candles · high 215 · low 138 · last 210                           │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { candlestick } from "@ifelse.codes/chitra";

candlestick({
  title: "CHRX — 10-Day Price Action",
  data: [
    { open: 142, high: 158, low: 138, close: 155, label: "Jan 8" },
    { open: 155, high: 168, low: 148, close: 151, label: "Jan 9" },
    { open: 151, high: 163, low: 143, close: 161, label: "Jan10" },
    { open: 161, high: 182, low: 158, close: 178, label: "Jan11" },
    { open: 178, high: 185, low: 162, close: 165, label: "Jan12" },
    { open: 165, high: 174, low: 155, close: 170, label: "Jan15" },
    { open: 170, high: 192, low: 167, close: 188, label: "Jan16" },
    { open: 188, high: 196, low: 176, close: 179, label: "Jan17" },
    { open: 179, high: 198, low: 178, close: 195, label: "Jan18" },
    { open: 195, high: 215, low: 190, close: 210, label: "Jan19" },
  ],
  height: 16,
  width: 72,
  theme: "dracula",
}).render();`,
    group: "Trend & time",
  },
  {
    id: "treemap",
    name: "Treemap",
    description: "Hierarchical area chart whose intensity is a grey tone ramp, with the single peak node marked in the accent hue.",
    preview: `┌╌ Codebase ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ AREA                                           │
│ +█TS█████████████████▓Python▓▓▓▓▓▓▓▒Rust▒▒░Go░ │
│ │█45█████████████████▓30▓▓▓▓▓▓▓▓▓▓▓▒15▒▒▒▒░7░░ │
│ │████████████████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒░░░░ │
│ │████████████████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒░░░░ │
│ │████████████████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒░░░░ │
│ │████████████████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒░░░░ │
│ │████████████████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒░░░░ │
│ │████████████████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒░░░░ │
│ │████████████████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒░░░░ │
│ │████████████████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒░░░░ │
│ 5 leaves · peak TS                             │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { treemap } from "@ifelse.codes/chitra";

treemap({
  data: [
    { label: "TS",     value: 45 },
    { label: "Python", value: 30 },
    { label: "Rust",   value: 15 },
    { label: "Go",     value: 7  },
    { label: "Ruby",   value: 3  },
  ],
  title: "Codebase",
  width: 50,
  height: 10,
}).render();`,
    group: "Part-to-whole",
  },
  {
    id: "sankey",
    name: "Sankey Diagram",
    description: "Flow diagram showing how quantities move between nodes.",
    preview: `┌╌ SANKEY ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│ ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ │
│ FLOW 120                                    │
│ Users      ████████████████ Free       [60] │
│ Users      ▒▒▒▒▒▒▒▒ Pro        [30]         │
│ Users      ░░░ Enterprise [10]              │
│ Free       ▒▒▒▒▒ Churned    [20]            │
│ Nodes:                                      │
│   ■ Users  out:100                          │
│   ■ Free  in:60  out:20                     │
│   ■ Pro  in:30                              │
│   ■ Churned  in:20                          │
│   ■ Enterprise  in:10                       │
│ NODES 5 · LINKS 4 · PEAK Users → Free 60    │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘`,
    code: `import { sankey } from "@ifelse.codes/chitra";

sankey({
  nodes: ["Users", "Free", "Pro", "Enterprise", "Churned"],
  links: [
    { source: 0, target: 1, value: 60 },
    { source: 0, target: 2, value: 30 },
    { source: 0, target: 3, value: 10 },
    { source: 1, target: 4, value: 20 },
  ],
  width: 52,
}).render();`,
    group: "Flow & accumulation",
  },
];
