#!/usr/bin/env node
// Keep packages/core/src/version.ts equal to packages/core/package.json's version.
//
// Why this exists (S41 requirement 2): VERSION is exported public API. A literal
// in src/index.ts shipped to npm as "0.1.0" while the manifest said 0.3.0, and
// nothing failed. The fix is not a better literal — it is removing the human
// from the loop. The version is machine-derived from the manifest, and CI plus
// scripts/verify-session-41.sh run `--check`, so a bump that forgets to re-run
// this is a red build, not a silent lie.
//
//   node scripts/sync-version.mjs          write the file
//   node scripts/sync-version.mjs --check  exit 1 if stale (for CI)
import { readFileSync, writeFileSync } from "node:fs";

const pkgPath = new URL("../packages/core/package.json", import.meta.url);
const outPath = new URL("../packages/core/src/version.ts", import.meta.url);

const { version } = JSON.parse(readFileSync(pkgPath, "utf8"));

const contents = `// GENERATED by scripts/sync-version.mjs — do not edit by hand.
// Run \`node scripts/sync-version.mjs\` after bumping packages/core/package.json.
// CI runs it with --check, so this file cannot drift from the manifest.
export const VERSION = ${JSON.stringify(version)};
`;

const check = process.argv.includes("--check");
const current = (() => {
  try {
    return readFileSync(outPath, "utf8");
  } catch {
    return null;
  }
})();

if (check) {
  if (current !== contents) {
    console.error(
      `FAIL: packages/core/src/version.ts is out of date with package.json (${version}).\n` +
        `      Run: node scripts/sync-version.mjs`,
    );
    process.exit(1);
  }
  console.log(`OK: src/version.ts matches the manifest (${version})`);
} else {
  writeFileSync(outPath, contents);
  console.log(`wrote packages/core/src/version.ts — ${version}`);
}
